AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CertificateArn:
    Type: String
    Description: ARN of the Certificate to assign to the Listener.
  TargetGroupArn:
    Type: String
    Description: ARN of the Target Group to assign to the Listener.
  LoadBalancerArn:
    Type: String
    Description: ARN of the Load Balancer to assign the Listener to.
Resources:
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupArn
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-FS-1-2-Res-2019-08
Outputs:
  TargetGroupArn:
    Description: ARN of the Target Group assigned to the Listener.
    Value: !Ref TargetGroupArn
