AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  UserName:
    Description: 'The user to generate a key for.'
    Type: String
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    MinLength: 3
    MaxLength: 128
Resources:
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref UserName
Outputs:
  AccessKeyId:
    Description: Access Key Id
    Value: !Ref AccessKey
  SecretAccessKey:
    Description: Secret Access Key
    Value: !GetAtt AccessKey.SecretAccessKey
