AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Key:
    Type: AWS::KMS::Key
    Properties:
      Description: CMK for use with Elasticache.
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - !Sub "arn:aws:iam::${AWS::AccountId}:root"
          Action: kms:*
          Resource: "*"
        - Effect: Allow
          Principal:
            Service: "elasticache.amazonaws.com"
          Action:
          - "kms:DescribeKey"
          - "kms:Encrypt"
          - "kms:Decrypt"
          - "kms:ReEncrypt*"
          - "kms:GenerateDataKey"
          - "kms:GenerateDataKeyWithoutPlaintext"
          Resource: "*"
Outputs:
  KeyId:
    Description: The Key Id.
    Value: !GetAtt Key.KeyId
