AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC Id.
  CidrBlock:
    Type: String
    Description: The CIDR Block.
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: The AZ for the subnet.
Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref CidrBlock
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: false
Outputs:
  SubnetId:
    Description: The Subnet Id.
    Value: !Ref Subnet
