AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CacheNodeType:
    Type: String
    Description: The instance type to use for the cache node(s).
    AllowedValues:
      - cache.m5.large
      - cache.m5.xlarge
      - cache.m5.2xlarge
      - cache.m5.4xlarge
      - cache.m5.12xlarge
      - cache.m5.24xlarge
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.t1.micro
      - cache.m1.small
      - cache.m1.medium
      - cache.m1.large
      - cache.m1.xlarge
      - cache.m3.medium
      - cache.m3.large
      - cache.m3.xlarge
      - cache.m3.2xlarge
      - cache.c1.xlarge
      - cache.r5.large
      - cache.r5.xlarge
      - cache.r5.2xlarge
      - cache.r5.4xlarge
      - cache.r5.12xlarge
      - cache.r5.24xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge
      - cache.m2.xlarge
      - cache.m2.2xlarge
      - cache.m2.4xlarge
      - cache.r3.large
      - cache.r3.xlarge
      - cache.r3.2xlarge
      - cache.r3.4xlarge
      - cache.r3.8xlarge
    Default: cache.t2.small
  CacheSubnetGroupName:
    Type: String
    Description: The name of the cache subnet group.
  KMSKeyId:
    Type: String
    Description: The KMS Key ID.
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The VPC Security Group Ids.
  AutomaticFailoverEnabled:
    Type: String
    Description: Enable automatic failover.
    Default: false
  MultiAZEnabled:
    Type: String
    Description: Enable multi-AZ (if enabled, NumCacheClusters must be > 1).
    Default: false
  ReplicasPerNodeGroup:
    Type: Number
    Description: The number of replicas per node group.
    Default: 0
Resources:
  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AtRestEncryptionEnabled: true
      AutomaticFailoverEnabled: !Ref AutomaticFailoverEnabled
      CacheNodeType: !Ref CacheNodeType
      CacheSubnetGroupName: !Ref CacheSubnetGroupName
      Engine: redis
      KmsKeyId: !Ref KMSKeyId
      MultiAZEnabled: !Ref MultiAZEnabled
      ReplicasPerNodeGroup: !Ref ReplicasPerNodeGroup
      ReplicationGroupDescription: Elasticache Redis Cluster.
      SecurityGroupIds: !Ref SecurityGroupIds
