AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole'
Outputs:
  Role:
    Description: Role
    Value: !Ref AutoScalingRole
  RoleArn:
    Description: Role ARN
    Value: !GetAtt AutoScalingRole.Arn
