variable "name" {}
variable "stack" {}
variable "environment" {}
variable "actions" {}
variable "resources" {}
variable "filename" {}
variable "function_name" {}
variable "handler" {}
variable "runtime" {}
variable "subnet_ids" {}
variable "security_group_ids" {}
